---
- name: Enable and start firewalld service
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
  become: true

- name: Configure firewalld ports for SunCavanaugh app
  ansible.posix.firewalld.
    port: "{{ host_port }}/tcp"
    permanent: true
    state: enabled
    zone: "public" 
    immediate: true
  become: true
